"""Rebuild metadata.json from a previously-generated data.js and/or existing media
files on disk, without downloading anything.

Use this when metadata.json was lost but you still have the gallery's data.js (it
embeds every record) and/or the media/ folder. metadata.json is the single source
of truth for "what's already downloaded" and for rebuilding the gallery, so
restoring it stops the downloader from re-fetching everything.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

# Fields that belong on a metadata record (everything else in data.js, like
# "thumbnail"/"href", is derived and regenerated by the gallery builder).
META_FIELDS = [
    "id", "prompt", "created_at", "media_type", "model",
    "parent_id", "source_url", "local_path", "canvas_id", "canvas_name",
]


def parse_data_js(path: Path) -> list[dict[str, Any]]:
    text = path.read_text(encoding="utf-8")
    match = re.search(r"=\s*(\[.*\])\s*;?\s*$", text, re.S)
    if not match:
        raise SystemExit(f"Could not parse {path}; expected 'window.GROK_ARCHIVE_DATA = [...]'.")
    return json.loads(match.group(1))


def record_from_media(media: dict[str, Any]) -> dict[str, Any]:
    record = {key: media.get(key) for key in META_FIELDS if key in media}
    record["id"] = str(media.get("id", ""))
    record["local_path"] = str(record.get("local_path", "")).replace("\\", "/")
    return record


def reindex(gallery_dir: Path, metadata: Path, data_js: Path) -> int:
    by_id: dict[str, dict[str, Any]] = {}

    # 1) Keep whatever is already in metadata.json.
    if metadata.exists():
        try:
            for rec in json.loads(metadata.read_text(encoding="utf-8")):
                if rec.get("id"):
                    by_id[str(rec["id"])] = rec
        except json.JSONDecodeError:
            print(f"warning: {metadata} is not valid JSON; ignoring it.")
    before_existing = len(by_id)

    # 2) Recover full history from data.js (groups -> media[]).
    from_data = 0
    if data_js.exists():
        try:
            groups = parse_data_js(data_js)
        except (SystemExit, json.JSONDecodeError, ValueError) as exc:
            groups = []
            print(f"warning: could not parse {data_js} ({exc}); relying on existing metadata + disk scan.")
        for group in groups:
            for media in group.get("media", []):
                rec = record_from_media(media)
                if rec["id"] and rec["id"] not in by_id:
                    by_id[rec["id"]] = rec
                    from_data += 1

    # 3) Catch any media files on disk with no record at all (minimal record).
    from_disk = 0
    for sub, media_type in (("media/images", "image"), ("media/videos", "video")):
        folder = gallery_dir / sub
        if not folder.exists():
            continue
        for file in folder.iterdir():
            if not file.is_file():
                continue
            file_id = file.stem
            if file_id in by_id:
                continue
            by_id[file_id] = {
                "id": file_id,
                "prompt": "",
                "created_at": None,
                "media_type": media_type,
                "model": None,
                "parent_id": None,
                "source_url": None,
                "local_path": f"{sub}/{file.name}",
            }
            from_disk += 1

    metadata.parent.mkdir(parents=True, exist_ok=True)
    tmp = metadata.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(list(by_id.values()), ensure_ascii=False), encoding="utf-8")
    tmp.replace(metadata)

    print(
        f"reindex: {len(by_id)} records "
        f"(kept {before_existing} existing, +{from_data} from data.js, +{from_disk} from disk)"
    )
    return len(by_id)


def main() -> None:
    parser = argparse.ArgumentParser(description="Rebuild metadata.json from data.js / existing media.")
    parser.add_argument("--gallery-dir", type=Path, default=Path("gallery"))
    parser.add_argument("--metadata", type=Path, default=Path("metadata.json"))
    parser.add_argument("--data-js", type=Path, default=None,
                        help="Default: <gallery-dir>/gallery_incremental/data.js")
    args = parser.parse_args()

    data_js = args.data_js or args.gallery_dir / "gallery_incremental" / "data.js"
    reindex(args.gallery_dir, args.metadata, data_js)


if __name__ == "__main__":
    main()
