"""Rebuild metadata.json from a previously-generated data.js and/or existing media
files on disk, without downloading anything.

Use this when metadata.json was lost but you still have the gallery's data.js (it
embeds every record) and/or the media/ folder. metadata.json is the single source
of truth for "what's already downloaded" and for rebuilding the gallery, so
restoring it stops the downloader from re-fetching everything.
"""

from __future__ import annotations

import argparse
import json
import os
import re
from pathlib import Path
from typing import Any

from mediautil import file_content_hash, media_shard

# Subtitle / metadata sidecars that sit next to a media file (and must travel with
# it), not media in their own right.
SIDECAR_EXTS = {".srt", ".vtt", ".json"}


def _relocate(media_file: Path, target_dir: Path, *, rename_on_collision: bool = False,
              new_stem: str | None = None) -> Path:
    """Move ``media_file`` and its subtitle sidecars into ``target_dir`` (same
    volume → atomic per file). Returns the media file's new path. ``new_stem``
    renames the file (and its sidecars) — used to give disk-scanned files a stable
    content-addressed id instead of whatever name they were dropped under. With
    ``rename_on_collision`` a name clash in the target gets a ``__N`` suffix
    (used for the quarantine bin, where unrelated files can share a name)."""
    target_dir.mkdir(parents=True, exist_ok=True)
    suffix = media_file.suffix
    stem = new_stem or media_file.stem
    if rename_on_collision and (target_dir / f"{stem}{suffix}").exists():
        n = 1
        while (target_dir / f"{stem}__{n}{suffix}").exists():
            n += 1
        stem = f"{stem}__{n}"
    dest = target_dir / f"{stem}{suffix}"
    if dest.resolve() != media_file.resolve():
        os.replace(media_file, dest)
    for ext in (".srt", ".vtt"):
        side = media_file.with_suffix(ext)
        if side.is_file():
            side_dest = target_dir / f"{stem}{ext}"
            if side_dest.resolve() != side.resolve():
                os.replace(side, side_dest)
    return dest

# Fields that belong on a metadata record (everything else in data.js, like
# "thumbnail"/"href", is derived and regenerated by the gallery builder).
META_FIELDS = [
    "id", "prompt", "created_at", "media_type", "model",
    "parent_id", "source_url", "local_path", "canvas_id", "canvas_name",
]


def parse_data_js(path: Path) -> list[dict[str, Any]]:
    text = path.read_text(encoding="utf-8")
    match = re.search(r"=\s*(\[.*\])\s*;?\s*$", text, re.S)
    if not match:
        raise SystemExit(f"Could not parse {path}; expected 'window.GROK_ARCHIVE_DATA = [...]'.")
    return json.loads(match.group(1))


def record_from_media(media: dict[str, Any]) -> dict[str, Any]:
    record = {key: media.get(key) for key in META_FIELDS if key in media}
    record["id"] = str(media.get("id", ""))
    record["local_path"] = str(record.get("local_path", "")).replace("\\", "/")
    return record


def reindex(gallery_dir: Path, metadata: Path, data_js: Path) -> int:
    by_id: dict[str, dict[str, Any]] = {}

    # 1) Keep whatever is already in metadata.json.
    if metadata.exists():
        try:
            for rec in json.loads(metadata.read_text(encoding="utf-8")):
                if rec.get("id"):
                    by_id[str(rec["id"])] = rec
        except json.JSONDecodeError:
            print(f"warning: {metadata} is not valid JSON; ignoring it.")
    before_existing = len(by_id)

    # 2) Recover full history from data.js (groups -> media[]).
    from_data = 0
    if data_js.exists():
        try:
            groups = parse_data_js(data_js)
        except (SystemExit, json.JSONDecodeError, ValueError) as exc:
            groups = []
            print(f"warning: could not parse {data_js} ({exc}); relying on existing metadata + disk scan.")
        for group in groups:
            for media in group.get("media", []):
                rec = record_from_media(media)
                if rec["id"] and rec["id"] not in by_id:
                    by_id[rec["id"]] = rec
                    from_data += 1

    # Content-hash index of everything already recorded, so a freshly dropped-in
    # file that duplicates an existing item is quarantined rather than imported
    # again. Backfill the hash onto records that lack it (one-time cost per file).
    known_hashes: dict[str, str] = {}
    recorded_paths: set[str] = set()
    backfilled = 0
    for rec in by_id.values():
        lp = str(rec.get("local_path") or "").replace("\\", "/")
        if not lp:
            continue
        recorded_paths.add(lp)
        f = gallery_dir / lp
        if not f.is_file():
            continue
        h = rec.get("content_hash")
        if not h:
            try:
                h = file_content_hash(f)
            except OSError:
                continue
            rec["content_hash"] = h
            backfilled += 1
        known_hashes.setdefault(h, rec["id"])

    # 3) Catch media files on disk with no record. An already-recorded file (its
    #    path is in metadata) is skipped cheaply without hashing. An unrecognized
    #    file gets a **content-addressed id** (its blake2b hash) — so any filename
    #    works, even a dumb/repeated one like "1.mp4", with no id collision — and
    #    is sharded into media/<type>/<ab>/<hash>.<ext>, keeping its original name
    #    in ``orig_filename``. An exact duplicate of something already known is
    #    moved to media/_duplicates/ and skipped. Recurses over both layouts.
    dup_dir = gallery_dir / "media" / "_duplicates"
    from_disk = 0
    quarantined = 0
    for sub, media_type in (("media/images", "image"), ("media/videos", "video")):
        folder = gallery_dir / sub
        if not folder.exists():
            continue
        for file in sorted(folder.rglob("*")):
            if not file.is_file() or file.suffix.lower() in SIDECAR_EXTS:
                continue
            rel = file.relative_to(gallery_dir).as_posix()
            if rel in recorded_paths:
                continue  # already in the library at this exact path
            try:
                h = file_content_hash(file)
            except OSError:
                continue
            if h in known_hashes:
                _relocate(file, dup_dir, rename_on_collision=True)
                quarantined += 1
                continue
            new_id = h  # content-addressed: independent of the (possibly dumb) filename
            orig_name = file.name
            dest = _relocate(file, folder / media_shard(new_id), new_stem=new_id)
            new_rel = dest.relative_to(gallery_dir).as_posix()
            by_id[new_id] = {
                "id": new_id,
                "prompt": "",
                "created_at": None,
                "media_type": media_type,
                "model": None,
                "parent_id": None,
                "source_url": None,
                "local_path": new_rel,
                "content_hash": h,
                "orig_filename": orig_name,
            }
            known_hashes[h] = new_id
            recorded_paths.add(new_rel)
            from_disk += 1

    metadata.parent.mkdir(parents=True, exist_ok=True)
    tmp = metadata.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(list(by_id.values()), ensure_ascii=False), encoding="utf-8")
    tmp.replace(metadata)

    print(
        f"reindex: {len(by_id)} records (kept {before_existing} existing, "
        f"+{from_data} from data.js, +{from_disk} from disk, "
        f"{quarantined} duplicate(s) quarantined, {backfilled} hashes backfilled)"
    )
    return len(by_id)


def main() -> None:
    parser = argparse.ArgumentParser(description="Rebuild metadata.json from data.js / existing media.")
    parser.add_argument("--gallery-dir", type=Path, default=Path("gallery"))
    parser.add_argument("--metadata", type=Path, default=Path("metadata.json"))
    parser.add_argument("--data-js", type=Path, default=None,
                        help="Default: <gallery-dir>/gallery_incremental/data.js")
    args = parser.parse_args()

    data_js = args.data_js or args.gallery_dir / "gallery_incremental" / "data.js"
    reindex(args.gallery_dir, args.metadata, data_js)


if __name__ == "__main__":
    main()
